database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  name: blog
  charset: utf8mb4
  parseTime: true
  loc: Local
  maxIdleConns: 5
  maxOpenConns: 10
  connMaxLifetime: 1800

server:
  port: 8080

redis:
  addr: 127.0.0.1:6379
  password: 123456
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

website:
  url: http://你的主域名或ip
# 其他配置...


upload:
  mode: "oss"
  oss:
    url: "http://blog-felix.oss-cn-beijing.aliyuncs.com/"
    endpoint: "oss-cn-beijing.aliyuncs.com"
    accessKeyId: "LTAI5tHmZ47AR1CgaGR8fi4z"
    accessKeySecret: "ulJIX3GYn9SjUrDc2g971DqJEI6L0q"
    bucketName: "blog-felix"

search:
  mode: mysql

email:
  host: "smtp.qq.com"
  port: 587
  username: "793302276@qq.com"
  password: "wwtenafqarhubdbb"
  from: "793302276@qq.com"
